### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [tamada/uniq2#5]
Dear @tamada,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by tamada** [comment]
@sergeevabc Thank you for your request.
I will generate an executable for the Windows platform, soon.

**Comment by tamada** [comment]
Please find windows binary of uniq2 at 
https://github.com/tamada/uniq2/releases/tag/v1.0.2

**Comment by sergeevabc** [comment]
@tamada, thank you for a quick reply, it works as expected on Windows 7 x64.
However, its performance leaves much to be desired as follows

```console
$ stat -c%s hostnames.txt
1241429

$ procprofile -u -- uniq2 hostnames.txt out_uniq2.txt

Process ID       : 5064
Thread ID        : 1636
Process Exit Code: 0
Thread Exit Code : 0

User Time        : 10.389s                              <---------- !!!
Kernel Time      : 0.046s
Process Time     : 10.435s
Clock Time       : 10.582s

Working Set      : 21096 KB
Paged Pool       : 98 KB
Nonpaged Pool    : 10 KB
Pagefile         : 30124 KB
Page Fault Count : 5315

IO Read          : 1236 KB (in 306 reads)
IO Write         : 1184 KB (in 297 writes)
IO Other         : 2 KB (in 287 others)

$ procprofile -u -- awk "NF && !line[$0]++" hostnames.txt > out_awk.txt

Process ID       : 3772
Thread ID        : 1876
Process Exit Code: 0
Thread Exit Code : 0

User Time        : 0.296s
Kernel Time      : 0.124s
Process Time     : 0.420s
Clock Time       : 0.411s

Working Set      : 8848 KB
Paged Pool       : 111 KB
Nonpaged Pool    : 8 KB
Pagefile         : 5764 KB
Page Fault Count : 2260

IO Read          : 1238 KB (in 2747 reads)
IO Write         : 1184 KB (in 63095 writes)
IO Other         : 2 KB (in 255 others)

$ sha1sum *.txt
6a2fdfa174fde52cdb17c0d7cbcd4d48400ad8ed  hostnames.txt
289275d8ecab847e68303beacf8392949301f8a6  out_awk.txt
289275d8ecab847e68303beacf8392949301f8a6  out_uniq2.txt
```

Used
- [hostnames.zip](https://github.com/tamada/uniq2/files/4304625/hostnames.zip)
- [Procprofile][1] 1.5 x64
- AWK from [BusyBox][2] v1.32.0 ([GIT][3]’s ```awk``` 5.0 is even faster: 0.093s)
 
[1]: https://encode.su/threads/1838-Command-Line-Process-Profiling-Tool?p=35998&viewfull=1#post35998
[2]: https://frippery.org/busybox/
[3]: https://github.com/git-for-windows/git/releases/

**Comment by tamada** [comment]
@sergeevabc 
Thank you for your information.
In the current implementation, I do not care about runtime performance.
However, I will try to improve the issue in the near future.
